In [1]:
import numpy as np
import random as rd
import matplotlib.pyplot as plt

# Variables

In [2]:
#maxVM
K=3
#CapaTot
B=10
b=2
d=1
#Coût
Cf=1
Ca=1
Cd=1
Ch=1

# Transition et Reward

## Transition avec Proba PA(i)

s=[min(B,max(0,m+i-j*d)),j]

## Reward

if j>n:

    r=j*Cf+(j-n)*Ca+m*Ch

else:

    r=j*Cf+(n-j)*Cd+m*Ch

In [3]:
def Reward(A,S,B=B,K=K,Ca=Ca,Cd=Cd,Ch=Ch):
    R=np.zeros((len(S),len(A)))
    for j in range(len(A)):
        for s in range(len(S)):
            m,n=s%(B+1),s//(B+1)
            if j>n:
                R[s,j]=j*Cf+(j-n)*Ca+m*Ch
            else:
                R[s,j]=j*Cf+(n-j)*Cd+m*Ch
    return R

def Transition(A,S,PA,B=B,K=K,d=d):
    T=np.zeros((len(A),len(S),len(S)))
    for j in range(len(A)):
        for s in range(len(S)):
            for i in range(len(PA)):
                m=s%(B+1)
                pos=min(B,max(0,m+i-j*d))
                T[j][s][j*(K+1)+pos]+=PA[i]
    return T

def revertS(politique_optimale,B=B,K=K):
    PO=np.zeros((B+1,K+1))
    for s in range((B+1)*(K+1)):
        PO[s%(B+1),s//(B+1)]=politique_optimale[s]
    return PO

In [4]:
S=np.array([m+n*(B+1) for n in range(K+1) for m in range(B+1)])
A=np.array([k for k in range(K+1)])
PA=np.ones(b+1)/(b+1)
#PA=np.array([0.5,0.3,0.2])

T=Transition(A,S,PA)
R=Reward(A,S)
epsilon=0.01
gamma=0.9

# Q Value

In [5]:
def Q_value(S,A,T=T,R=R,gamma=gamma,epsilon=epsilon):
    
    Q=np.zeros((len(S),len(A)))
    k=0
    
    while True:
        Q_n1=np.copy(Q)
        k+=1
        for s in S:
            for j in A:
                Somme=R[s,j]
                for s2 in S:
                   Somme+=gamma*T[j,s,s2]*np.min(Q_n1[s2,:])
                Q[s,j]=Somme
        if np.max(np.abs(Q-Q_n1))<epsilon:
            break
        else:
            print(k)
    politique_optimale = {s: np.argmin(Q[s, :]) for s in S}
    
    return Q,politique_optimale

In [6]:
Q,politique_optimale=Q_value(S,A)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58


In [7]:
revertS(politique_optimale)

array([[0., 0., 0., 0.],
       [0., 0., 0., 3.],
       [0., 0., 3., 3.],
       [0., 0., 3., 3.],
       [0., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
Q[10]

array([53.83160765, 48.71087952, 52.37460944, 56.30759485])

In [9]:
politique_optimale

{0: 0,
 1: 0,
 2: 0,
 3: 0,
 4: 0,
 5: 2,
 6: 2,
 7: 1,
 8: 1,
 9: 1,
 10: 1,
 11: 0,
 12: 0,
 13: 0,
 14: 0,
 15: 2,
 16: 2,
 17: 2,
 18: 1,
 19: 1,
 20: 1,
 21: 1,
 22: 0,
 23: 0,
 24: 3,
 25: 3,
 26: 2,
 27: 2,
 28: 2,
 29: 1,
 30: 1,
 31: 1,
 32: 1,
 33: 0,
 34: 3,
 35: 3,
 36: 3,
 37: 2,
 38: 2,
 39: 2,
 40: 1,
 41: 1,
 42: 1,
 43: 1}

# Q learning

In [10]:
S

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43])

# Sarsa